
name: CI

on:
  push:
    branches: [ master ]
  
  schedule:
    - cron: "0 */6 * * *"   

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: Platane/snk@v1
        with:
            github_user_name: ${{ github.repository_owner }}
            svg_out_path: dist/github-contributions-grid.svg
            
      - name: push github-contributions-grid.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
